version: '3.7'

services:
  fastapi:
    image: backend_chat_fastapi
    build:
      context: ./backend/chat_api
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app 

  nextjs:  # Name of your Next.js service
    image: frontend_nextjs
    build:
      context: ./frontend  
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app  # Replace with your actual Next.js directory path relative to this docker-compose file
      - /usr/src/app/node_modules
